# Generated by Django 5.2.4 on 2025-07-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_description',
            new_name='description',
        ),
    ]
