# Generated by Django 5.2.4 on 2025-07-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_description_blog_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='blog_description',
        ),
    ]
