# Generated by Django 5.2.4 on 2025-07-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_like_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
